#### ARRAYS

In [1]:
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    a=numpy.array(arr,float)
    return(a[::-1])

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


#### SHAPE AND RESHAPE

In [2]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import numpy as np

a=np.array(input().strip().split(' '),int)
a.shape=(3,3)
print(a)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### TRANSPOSE AND FLATTEN

In [3]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import numpy as np

n, m = [int(x) for x in input().split()]
a=np.zeros((n,m),int)
for i in range(n):
    arr=input().strip().split(' ')
    a[i]=np.array(arr,int)

print(np.transpose(a))
print(a.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


#### CONCATENATE

In [4]:
import numpy as np

n,m,p=[int(x) for x in input().split()]
a=np.zeros((n,p),int)
b=np.zeros((m,p),int)
for i in range(n):
    arr=input().strip().split(' ')
    a[i]=np.array(arr,int)

for i in range(m):
    arr=input().strip().split(' ')
    b[i]=np.array(arr,int)
    
print(np.concatenate((a,b),axis=0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


#### ZEROS AND ONES

In [5]:
import numpy

N = tuple(map(int,input().split()))

                
print(numpy.zeros(N, int)) 
print(numpy.ones(N, int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


#### EYE AND IDENTITY

In [6]:
import numpy as np
np.set_printoptions(legacy='1.13')

n,m=[int(x) for x in input().split()]
a=np.eye(n,m,k=0)
print(a)

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


#### ARRAY MATHEMATICS

In [7]:
import numpy as np

n,m=[int(x) for x in input().split()]
a=np.zeros((n,m),int)
b=np.zeros((n,m),int)
for i in range(n):
    arr=input().strip().split(' ')
    a[i]=np.array(arr,int)
    
for i in range(n):
    arr=input().strip().split(' ')
    b[i]=np.array(arr,int)
    
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(a//b)
print(np.mod(a,b))
print(np.power(a,b))

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


#### FLOOR, CEIL AND RINT

In [8]:
import numpy as np
np.set_printoptions(legacy='1.13')

a=np.array((input().strip().split(' ')),float)
print(np.floor(a))
print(np.ceil(a))
print(np.rint(a))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


#### SUM AND PROD

In [9]:
import numpy as np

n,m=[int(x) for x in input().split()]

a=np.zeros((n,m),int)
for i in range(n):
    a[i]=np.array((input().strip().split(' ')),int)
    
b=np.sum(a,axis=0)
print(np.prod(b))

2 2
1 2
3 4
24


#### MIN AND MAX

In [10]:
import numpy as np

n,m=[int(x) for x in input().split()]
a=np.zeros((n,m),int)
for i in range(n):
    a[i]=np.array((input().strip().split(' ')),int)
    
b=np.min(a,axis=1)
print(np.max(b))

4 2
2 5
3 7
1 3
4 0
3


#### MEAN, VAR, AND STD

In [12]:
import numpy as np

n,m=[int(x) for x in input().split()]
a=np.zeros((n,m),int)
for i in range(n):
    a[i]=np.array((input().strip().split(' ')),int)
    
print(np.mean(a,axis=1))
print(np.var(a,axis=0))
print(np.std(a,axis=None))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


#### DOT AND CROSS

In [13]:
# Enter your code here. Read input from STDIN. Print output to STDOUTimport numpy
import numpy as np
n = int(input())
a=np.zeros((n,n),int)
b=np.zeros((n,n),int)
for i in range(n):
    a[i]=np.array((input().strip().split(' ')),int)
    
for i in range(n):
    b[i]=np.array((input().strip().split(' ')),int)
# A = numpy.array([ map(int, input().split()) for i in range(N) ])
# B = numpy.array([ map(int, input().split()) for i in range(N) ])

print(np.dot(a, b))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


#### INNER AND OUTER

In [14]:
import numpy as np

a=np.array((input().strip().split(' ')),int)
b=np.array((input().strip().split(' ')),int)

print(np.inner(a,b))
print(np.outer(a,b))

0 1
2 3
3
[[0 0]
 [2 3]]


#### POLYNOMIALS

In [15]:
import numpy as np

a=np.array((input().strip().split(' ')),float)
x=int(input())
print(np.polyval(a,x))

1.1 2 3
0
3.0


#### LINEAR ALGEBRA

In [16]:
import numpy as np

n=int(input())
a=np.zeros((n,n),float)
for i in range(n):
    a[i]=np.array((input().strip().split(' ')),float)
    
print("%0.2f" %(np.linalg.det(a)))

2
1.1 1.1
1.1 1.2
0.11
